package com.example.workdemo.mapper;

import com.example.workdemo.entity.Employees;
import com.example.workdemo.entity.EmployeesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    long countByExample(EmployeesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    int deleteByExample(EmployeesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    int deleteByPrimaryKey(Integer employeenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    int insert(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    int insertSelective(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    List<Employees> selectByExample(EmployeesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    Employees selectByPrimaryKey(Integer employeenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    int updateByExampleSelective(@Param("record") Employees record, @Param("example") EmployeesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    int updateByExample(@Param("record") Employees record, @Param("example") EmployeesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    int updateByPrimaryKeySelective(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    int updateByPrimaryKey(Employees record);
}