package com.example.workdemo.mapper;

import com.example.workdemo.entity.OrderDetails;
import com.example.workdemo.entity.OrderDetailsExample;
import com.example.workdemo.entity.OrderDetailsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    long countByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int deleteByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int deleteByPrimaryKey(OrderDetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int insert(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int insertSelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    List<OrderDetails> selectByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    OrderDetails selectByPrimaryKey(OrderDetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int updateByExampleSelective(@Param("record") OrderDetails record, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int updateByExample(@Param("record") OrderDetails record, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int updateByPrimaryKeySelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int updateByPrimaryKey(OrderDetails record);
}