package com.example.workdemo.mapper;

import com.example.workdemo.entity.ProductLines;
import com.example.workdemo.entity.ProductLinesExample;
import com.example.workdemo.entity.ProductLinesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductLinesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    long countByExample(ProductLinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int deleteByExample(ProductLinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int deleteByPrimaryKey(String productline);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int insert(ProductLinesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int insertSelective(ProductLinesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    List<ProductLinesWithBLOBs> selectByExampleWithBLOBs(ProductLinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    List<ProductLines> selectByExample(ProductLinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    ProductLinesWithBLOBs selectByPrimaryKey(String productline);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int updateByExampleSelective(@Param("record") ProductLinesWithBLOBs record, @Param("example") ProductLinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int updateByExampleWithBLOBs(@Param("record") ProductLinesWithBLOBs record, @Param("example") ProductLinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int updateByExample(@Param("record") ProductLines record, @Param("example") ProductLinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int updateByPrimaryKeySelective(ProductLinesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int updateByPrimaryKeyWithBLOBs(ProductLinesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlines
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    int updateByPrimaryKey(ProductLines record);
}