package com.example.workdemo.entity;

public class Items {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.id
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_no
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    private String itemNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.id
     *
     * @return the value of items.id
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.id
     *
     * @param id the value for items.id
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_no
     *
     * @return the value of items.item_no
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_no
     *
     * @param itemNo the value for items.item_no
     *
     * @mbg.generated Mon Apr 03 21:24:45 HKT 2023
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }
}