package com.example.workdemo.entity;

public class Tokens {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tokens.s
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    private String s;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tokens.s
     *
     * @return the value of tokens.s
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    public String getS() {
        return s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tokens.s
     *
     * @param s the value for tokens.s
     *
     * @mbg.generated Mon Apr 03 22:56:19 HKT 2023
     */
    public void setS(String s) {
        this.s = s == null ? null : s.trim();
    }
}